services:
  - docker

os: linux

script:
  - ./build.sh
  - docker-compose up -d
  - curl -LO https://www-us.apache.org/dist/kafka/2.3.1/kafka_2.12-2.3.1.tgz && tar -xf kafka_2.12-2.3.1.tgz && export PATH=$PWD/kafka_2.12-2.3.1/bin:$PATH
  - ./create-topics.sh
  - ./ci-test.sh
  - docker-compose down

