services:
  - docker

os: linux

install:
  - mkdir -p ~/bin && export PATH=~/bin:$PATH
    # Install kind
  - curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.0/kind-$(uname)-amd64 && chmod +x ./kind && mv ./kind ~/bin
    # Install kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl && chmod +x ./kubectl && mv ./kubectl ~/bin

script:
    # Build docker images for the services
  - ./build.sh
    # Start a local K8s cluster using kind, configured with a local Docker registry
  - ./.ci/local-cluster.sh
    # Push images to local registry
  - ./.ci/local-registry.sh
    # Update deployments to reference the local registry
  - ./.ci/replace-refs.sh
    # Deploy to local cluster
  - kubectl create ns coffeeshop-demo
  - ./apply-kubernetes.sh
    # Wait for kafka to be ready
  - export PODNAME=`kubectl get pod -l app=kafka -o jsonpath="{.items[0].metadata.name}" -n coffeeshop-demo`
  - kubectl wait --for=condition=Ready pod -l app=kafka -n coffeeshop-demo --timeout=180s || kubectl logs $PODNAME -n coffeeshop-demo
    # Wait for all pods to be ready
  - export PODNAME=`kubectl get pod -l app=barista-kafka -o jsonpath="{.items[0].metadata.name}" -n coffeeshop-demo`
  - kubectl wait --for=condition=Ready pod -l app=barista-kafka -n coffeeshop-demo --timeout=120s || kubectl logs $PODNAME -n coffeeshop-demo
  - export PODNAME=`kubectl get pod -l app=barista-http -o jsonpath="{.items[0].metadata.name}" -n coffeeshop-demo`
  - kubectl wait --for=condition=Ready pod -l app=barista-http -n coffeeshop-demo --timeout=120s || kubectl logs $PODNAME -n coffeeshop-demo
  - export PODNAME=`kubectl get pod -l app=coffeeshop-service -o jsonpath="{.items[0].metadata.name}" -n coffeeshop-demo`
  - kubectl wait --for=condition=Ready pod -l app=coffeeshop-service -n coffeeshop-demo --timeout=120s || kubectl logs $PODNAME -n coffeeshop-demo
    # Display overall system state
  - kubectl get all -n coffeeshop-demo
    # Forward local port
  - kubectl port-forward service/coffeeshop-service 8080:8080 -n coffeeshop-demo &
    # Wait for port forwarding, test system
  - sleep 5 && ./ci-test.sh
