version: '2'

services:

  zookeeper:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties 
      --override listeners=$${KAFKA_LISTENERS} 
      --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} 
      --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT} 
      --override listener.security.protocol.map=$${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP} 
      --override inter.broker.listener.name=$${KAFKA_INTER_BROKER_LISTENER_NAME}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE

  barista-kafka:
      image: barista-kafka
      command: [
          "java", "-Dkafka.bootstrap.servers=kafka:9093", "-jar", "app.jar"
      ]
      depends_on:
          - kafka
      ports:
          - "8090:8090"

  barista-http:
      image: barista-http
      command: [
          "java", "-Dkafka.bootstrap.servers=kafka:9093", "-jar", "app.jar"
      ]
      depends_on:
          - kafka
      ports:
          - "8082:8082"

  coffeeshop-service:
      image: coffeeshop-service
      command: [
          "java", "-Dkafka.bootstrap.servers=kafka:9093", "-Dme.escoffier.quarkus.coffeeshop.http.BaristaService/mp-rest/url=http://barista-http:8082", "-jar", "app.jar"
      ]
      depends_on:
          - kafka
          - barista-http
      ports:
          - "8080:8080"
      expose:
          - "8080"
