apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
  - name: external
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: internal
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka
