apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: strimzi/kafka:0.11.3-kafka-2.1.0
        args:
          - sh
          - -c
          - bin/zookeeper-server-start.sh config/zookeeper.properties
        env:
          - name: LOG_DIR
            value: /tmp/logs
        ports:
          - containerPort: 2181
        imagePullPolicy: Never
