apiVersion: apps/v1
kind: Deployment
metadata:
  name: barista-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: barista-kafka
  template:
    metadata:
      labels:
        app: barista-kafka
    spec:
      containers:
      - name: barista-kafka
        image: barista-kafka
        ports:
          - containerPort: 8090
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 8090
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8090
        command: ["/opt/ol/wlp/bin/server",
          "run",
          "defaultServer",
          "-Dmp.messaging.connector.liberty-kafka.bootstrap.servers=kafka:9093"
        ]
