apiVersion: v1
kind: Service
metadata:
  name: barista-kafka-service-cluster-ip
spec:
  ports:
  - port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: barista-kafka-deployment
  type: ClusterIP