apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffeeshop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffeeshop-service
  template:
    metadata:
      labels:
        app: coffeeshop-service
    spec:
      containers:
      - name: coffeeshop-service
        image: coffeeshop-service
        ports:
          - containerPort: 8080
        imagePullPolicy: IfNotPresent
        livenessProbe:
          tcpSocket:
            port: 8080
          periodSeconds: 10
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080

