apiVersion: v1
kind: Service
metadata:
  name: coffeeshop-service-cluster-ip
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 3001
  selector:
    app: coffeeshop-service-deployment
  type: ClusterIP