apiVersion: v1
kind: Service
metadata:
  name: {{ include "baristaHttp.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
    name: http
  selector:
    app: barista-http
    release: {{ .Release.Name }}